import { Car } from "./types"

export const cars: Car[] = [
  {
    id: "toyota-camry-2024",
    brand: "Toyota",
    model: "Camry",
    year: 2024,
    bodyStyle: "sedan",
    fuelType: "hybrid",
    basePrice: 28400,
    maxPrice: 36785,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
    tagline: "America's best-selling sedan, now hybrid-only",
    description:
      "The 2024 Toyota Camry transitions to a hybrid-only powertrain, offering outstanding fuel efficiency without sacrificing performance. A perennial favorite for its legendary reliability, spacious cabin, and competitive pricing.",
    specs: {
      horsepower: 225,
      torque: 163,
      engine: "2.5L 4-Cylinder Hybrid",
      transmission: "CVT",
      driveType: "FWD",
      zeroToSixty: 7.1,
      topSpeed: 127,
      mpgCity: 51,
      mpgHighway: 53,
      mpgCombined: 52,
      cargo: 15.1,
      seating: 5,
    },
    trimLevels: [
      { name: "LE", price: 28400, highlights: ["Hybrid powertrain", "7-inch touchscreen", "Pre-collision system"] },
      { name: "SE", price: 29900, highlights: ["Sport-tuned suspension", "18-inch wheels", "Dual-zone climate"] },
      { name: "XLE", price: 33400, highlights: ["12.3-inch touchscreen", "Ventilated seats", "JBL audio"] },
      { name: "XSE", price: 34200, highlights: ["V6-style styling", "19-inch wheels", "Panoramic moonroof"] },
      { name: "XSE AWD", price: 36785, highlights: ["AWD system", "All-weather capability", "Sport appearance"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Toyota Safety Sense 3.0",
        "Pre-Collision System with Pedestrian Detection",
        "Lane Departure Alert",
        "Automatic High Beams",
        "Radar Cruise Control",
        "Blind Spot Monitor",
        "Rear Cross-Traffic Alert",
        "7 Airbags",
      ],
    },
    interiorFeatures: [
      "Dual-zone automatic climate control",
      "Heated front seats",
      "Leather-trimmed seats (XLE+)",
      "Power-adjustable driver seat",
      "Wireless charging pad",
      "USB-A and USB-C ports",
      "60/40 split-folding rear seat",
    ],
    exteriorFeatures: [
      "LED headlights and taillights",
      "Shark fin antenna",
      "Dual exhaust outlets",
      "18-inch alloy wheels (SE+)",
      "Power moonroof (SE+)",
      "Adaptive front lighting",
    ],
    techFeatures: [
      "Toyota Audio Multimedia system",
      "Wireless Apple CarPlay",
      "Wireless Android Auto",
      "Amazon Alexa integration",
      "Over-the-air software updates",
      "Digital rearview mirror (XLE+)",
      "Head-up display (XSE+)",
    ],
    pros: [
      "Exceptional fuel economy for a midsize sedan",
      "Toyota's legendary reliability record",
      "Roomy, comfortable interior",
      "Standard hybrid powertrain across all trims",
      "Competitive starting price",
    ],
    cons: [
      "Trunk space slightly reduced vs. V6 era",
      "CVT can feel sluggish under hard acceleration",
      "Rear legroom tight for taller passengers",
      "No manual transmission option",
    ],
    coolFeatures: [
      "Available AWD hybrid — rare in sedans",
      "Sport-tuned XSE variant mimics V6 performance feel",
      "Regenerative braking extends fuel efficiency further",
    ],
    colors: ["Midnight Black Metallic", "Wind Chill Pearl", "Supersonic Red", "Celestial Silver", "Ice Cap", "Reservoir Blue"],
  },
  {
    id: "tesla-model-3-2024",
    brand: "Tesla",
    model: "Model 3",
    year: 2024,
    bodyStyle: "sedan",
    fuelType: "electric",
    basePrice: 40240,
    maxPrice: 55990,
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
    tagline: "The EV that changed everything, now better than ever",
    description:
      "The refreshed 2024 Tesla Model 3 (Highland) brings a completely new interior, improved range, and refined driving dynamics. It remains the benchmark electric sedan for technology, performance, and charging network access.",
    specs: {
      horsepower: 358,
      torque: 430,
      engine: "Dual Motor Electric",
      transmission: "Single-Speed Direct Drive",
      driveType: "AWD",
      zeroToSixty: 4.2,
      topSpeed: 145,
      electricRange: 341,
      totalRange: 341,
      batteryCapacity: 82,
      chargingTime: "15 min (170 mi, Supercharger V3)",
      cargo: 22.9,
      seating: 5,
    },
    trimLevels: [
      { name: "RWD", price: 40240, highlights: ["272 mi range", "RWD", "0-60 in 5.8s"] },
      { name: "Long Range AWD", price: 47240, highlights: ["358 mi range", "AWD", "0-60 in 4.2s"] },
      { name: "Performance", price: 55990, highlights: ["315 mi range", "0-60 in 3.1s", "Sport suspension"] },
    ],
    safety: {
      rating: "5-Star Overall",
      ratingSource: "NHTSA 2024",
      features: [
        "Autopilot (standard)",
        "Full Self-Driving Capability (optional)",
        "Forward Collision Warning",
        "Automatic Emergency Braking",
        "Lane Departure Avoidance",
        "Blind Spot Monitoring",
        "8 airbags",
        "Sentry Mode",
      ],
    },
    interiorFeatures: [
      "15.4-inch center touchscreen",
      "Rear 8-inch touchscreen (new 2024)",
      "Ambient lighting",
      "Premium audio system (17 speakers)",
      "Heated and ventilated front seats",
      "Heated rear seats",
      "Glass roof",
    ],
    exteriorFeatures: [
      "Flush door handles",
      "Integrated rear spoiler",
      "LED light bar (front & rear)",
      "19-inch Photon Wheels (standard)",
      "Acoustic glass for noise reduction",
    ],
    techFeatures: [
      "Wireless software updates OTA",
      "Tesla Supercharger access (17,000+ stations)",
      "Live traffic navigation",
      "Video streaming (Netflix, YouTube)",
      "Gaming capabilities",
      "Voice commands",
      "Phone as key",
      "Dog Mode / Camp Mode",
    ],
    pros: [
      "Incredible charging network (Tesla Supercharger)",
      "Best-in-class tech and software",
      "Exhilarating performance",
      "Low running costs",
      "Regular free OTA improvements",
    ],
    cons: [
      "No Apple CarPlay or Android Auto",
      "Everything controlled via touchscreen (no physical buttons)",
      "Build quality inconsistencies reported",
      "No frunk storage in Model 3",
    ],
    coolFeatures: [
      "Full Self-Driving hardware included (subscription required)",
      "Dog Mode keeps pets comfortable with climate control + screen message",
      "Bioweapon Defense Mode HEPA filter (Performance only)",
      "Track Mode for Performance variant",
    ],
    colors: ["Pearl White Multi-Coat", "Solid Black", "Midnight Cherry Red", "Deep Blue Metallic", "Stealth Grey"],
  },
  {
    id: "ford-f150-2024",
    brand: "Ford",
    model: "F-150",
    year: 2024,
    bodyStyle: "truck",
    fuelType: "gasoline",
    basePrice: 36315,
    maxPrice: 80885,
    image: "https://images.unsplash.com/photo-1614484393797-257ee1d83a1e?w=800&q=80",
    tagline: "America's best-selling vehicle for 47 years running",
    description:
      "The Ford F-150 is the undisputed king of full-size pickups. Offering unmatched versatility, a wide range of powertrains (including hybrid), and clever features like the Pro Power Onboard generator, the F-150 does it all.",
    specs: {
      horsepower: 400,
      torque: 500,
      engine: "3.5L PowerBoost Hybrid V6",
      transmission: "10-Speed Automatic",
      driveType: "4WD",
      zeroToSixty: 5.5,
      topSpeed: 110,
      mpgCity: 24,
      mpgHighway: 24,
      mpgCombined: 24,
      cargo: 62.3,
      seating: 6,
      towingCapacity: 12700,
      payloadCapacity: 2235,
    },
    trimLevels: [
      { name: "Regular", price: 36315, highlights: ["3.3L V6", "Regular cab", "Work-ready"] },
      { name: "XLT", price: 44000, highlights: ["SuperCrew cab", "SYNC 4", "8-inch screen"] },
      { name: "Lariat", price: 54000, highlights: ["Leather seats", "Heated seats", "12-inch screen"] },
      { name: "King Ranch", price: 66000, highlights: ["Premium leather", "Unique badging", "Max equipment"] },
      { name: "Platinum", price: 72000, highlights: ["Massaging seats", "360 camera", "B&O Audio"] },
      { name: "Raptor", price: 80885, highlights: ["High-performance off-road", "37-inch tires", "Fox shocks"] },
    ],
    safety: {
      rating: "5-Star Overall",
      ratingSource: "NHTSA 2024",
      features: [
        "Ford Co-Pilot360",
        "Pre-Collision Assist",
        "Lane-Keeping System",
        "Auto High-Beam Headlamps",
        "Reverse Sensing System",
        "Pro Trailer Backup Assist",
        "Blind Spot Information System",
      ],
    },
    interiorFeatures: [
      "Interior Work Surface (fold-flat front seats)",
      "Max Recline Seats",
      "Zone Lighting",
      "Power tailgate",
      "Heated and ventilated front seats (Lariat+)",
      "Massaging front seats (Platinum+)",
      "Dual-zone climate control",
    ],
    exteriorFeatures: [
      "Military-grade aluminum alloy body",
      "BoxLink cargo management system",
      "LED headlights",
      "Retractable running boards (optional)",
      "Trailer hitch receiver",
      "Power deployable running boards (optional)",
    ],
    techFeatures: [
      "SYNC 4A with 12-inch screen",
      "Apple CarPlay / Android Auto",
      "Pro Power Onboard (2.0kW generator)",
      "FordPass Connect 4G LTE",
      "Onboard Scales (payload monitoring)",
      "Smart Hitch",
      "360-degree camera (Lariat+)",
    ],
    pros: [
      "Most capable full-size truck for towing and payload",
      "Huge range of configurations and powertrains",
      "Pro Power Onboard generator is genuinely useful",
      "Comfortable, truck-luxury interior options",
      "Best resale value among full-size trucks",
    ],
    cons: [
      "Fuel economy trails Chevy Silverado",
      "Large size makes urban parking challenging",
      "High-end trims get very expensive",
      "Aluminum body requires specialized repair",
    ],
    coolFeatures: [
      "Pro Power Onboard: up to 7.2kW of exportable power (like a generator on wheels)",
      "Interior Work Surface: front seats fold flat to create a desk",
      "Pro Trailer Backup Assist: steer the trailer with a knob",
    ],
    colors: ["Oxford White", "Agate Black", "Iconic Silver", "Rapid Red", "Atlas Blue", "Antimatter Blue"],
  },
  {
    id: "honda-crv-2024",
    brand: "Honda",
    model: "CR-V",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "plug-in hybrid",
    basePrice: 31895,
    maxPrice: 42240,
    image: "https://images.unsplash.com/photo-1623597780975-38ccd5030c83?w=800&q=80",
    tagline: "The world's best-selling SUV, now with plug-in power",
    description:
      "Honda's perennial best-seller gets a plug-in hybrid variant that offers 40 miles of electric-only range alongside a practical, spacious interior. The CR-V PHEV combines everyday EV efficiency with the confidence of gas backup.",
    specs: {
      horsepower: 204,
      torque: 247,
      engine: "2.0L 4-Cylinder PHEV",
      transmission: "E-CVT",
      driveType: "AWD",
      zeroToSixty: 7.8,
      topSpeed: 118,
      mpgCity: 40,
      mpgHighway: 36,
      mpgCombined: 38,
      electricRange: 40,
      totalRange: 450,
      batteryCapacity: 17.7,
      chargingTime: "2.5 hours (Level 2)",
      cargo: 39.3,
      seating: 5,
    },
    trimLevels: [
      { name: "Sport", price: 31895, highlights: ["Turbocharged gas", "18-inch wheels", "Honda Sensing"] },
      { name: "EX", price: 34395, highlights: ["Panoramic moonroof", "Heated seats", "Remote start"] },
      { name: "Sport-L PHEV", price: 38950, highlights: ["40-mile EV range", "AWD", "Wireless charging"] },
      { name: "Sport Touring PHEV", price: 42240, highlights: ["Bose audio", "HUD", "Leather seats"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Honda Sensing Suite",
        "Collision Mitigation Braking",
        "Road Departure Mitigation",
        "Lane Keeping Assist",
        "Adaptive Cruise Control",
        "Blind Spot Information",
        "Rear Cross-Traffic Monitor",
      ],
    },
    interiorFeatures: [
      "9-inch touchscreen",
      "Panoramic moonroof (EX+)",
      "Heated front seats",
      "Wireless charging pad",
      "USB-A and USB-C ports (front and rear)",
      "Hands-free power tailgate",
      "Rear air vents",
    ],
    exteriorFeatures: [
      "Full LED lighting",
      "Hands-free power tailgate",
      "Chrome exterior accents",
      "18-inch alloy wheels",
      "Roof rails",
      "Panoramic glass roof",
    ],
    techFeatures: [
      "Honda Sensing (standard on all trims)",
      "Wireless Apple CarPlay",
      "Wireless Android Auto",
      "Google Built-in (Sport Touring)",
      "Bose Premium Sound (Sport Touring)",
      "Head-up display (Sport Touring)",
      "Honda Connect app",
    ],
    pros: [
      "Excellent 40-mile EV range covers most daily commutes",
      "Spacious interior with best-in-class cargo room",
      "Outstanding reliability reputation",
      "Smooth, refined driving experience",
      "Great value for PHEV segment",
    ],
    cons: [
      "Infotainment system less intuitive than some rivals",
      "No third-row option",
      "PHEV adds significant weight",
      "Charging port placement is inconvenient",
    ],
    coolFeatures: [
      "Magic Seat rear bench for versatile cargo configurations",
      "PHEV mode lets you save battery for city driving",
      "One-motor EV mode is whisper quiet",
    ],
    colors: ["Sonic Gray Pearl", "Radiant Red Metallic", "Lunar Silver Metallic", "Crystal Black Pearl", "Aegean Blue"],
  },
  {
    id: "bmw-3series-2024",
    brand: "BMW",
    model: "3 Series",
    year: 2024,
    bodyStyle: "sedan",
    fuelType: "gasoline",
    basePrice: 43800,
    maxPrice: 59500,
    image: "https://images.unsplash.com/photo-1594051673969-172a6f721d3c?w=800&q=80",
    tagline: "The ultimate driving machine — still the benchmark",
    description:
      "The BMW 3 Series remains the definitive sports sedan benchmark. With its perfect 50/50 weight distribution, communicative steering, and powerful engine options, the 3 Series delivers an unmatched driving experience in the luxury compact segment.",
    specs: {
      horsepower: 382,
      torque: 369,
      engine: "3.0L TwinPower Turbo I6 (M340i)",
      transmission: "8-Speed Steptronic Sport",
      driveType: "AWD",
      zeroToSixty: 3.9,
      topSpeed: 155,
      mpgCity: 23,
      mpgHighway: 31,
      mpgCombined: 26,
      cargo: 17,
      seating: 5,
    },
    trimLevels: [
      { name: "330i", price: 43800, highlights: ["2.0L turbo 4-cyl", "255hp", "RWD or xDrive"] },
      { name: "330e PHEV", price: 47900, highlights: ["PHEV hybrid", "288hp combined", "20mi EV range"] },
      { name: "M340i", price: 57800, highlights: ["382hp inline-6", "0-60 in 3.9s", "Sport suspension"] },
      { name: "M340i xDrive", price: 59500, highlights: ["AWD", "M Sport exhaust", "Adaptive M suspension"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK",
      ratingSource: "IIHS 2024",
      features: [
        "Active Driving Assistant",
        "Frontal Collision Warning",
        "Lane Departure Warning",
        "Speed Limit Info",
        "Rear Cross-Traffic Alert",
        "Parking Assistant",
        "Surround View Camera",
      ],
    },
    interiorFeatures: [
      "iDrive 8 with 14.9-inch curved display",
      "BMW Intelligent Personal Assistant",
      "Ambient lighting (40+ colors)",
      "Heated front seats (standard)",
      "Harman Kardon surround sound",
      "Gesture control",
      "Panoramic sunroof",
    ],
    exteriorFeatures: [
      "Iconic kidney grille",
      "Adaptive LED headlights",
      "M Sport body kit (M340i)",
      "19-inch M alloy wheels",
      "Shadowline exterior trim",
      "Aerodynamic styling",
    ],
    techFeatures: [
      "BMW iDrive 8 OS",
      "Wireless Apple CarPlay / Android Auto",
      "BMW Maps navigation",
      "OTA software updates",
      "BMW Digital Key Plus",
      "Head-up display",
      "Wireless charging",
    ],
    pros: [
      "Best-in-class driving dynamics and steering feel",
      "Stunning, driver-focused interior",
      "Powerful and refined engine options",
      "iDrive 8 is one of the best infotainment systems",
      "Strong resale value for the segment",
    ],
    cons: [
      "Premium pricing and expensive options",
      "Rear seat space trails some rivals",
      "Maintenance costs higher than Japanese brands",
      "Some features cost extra that competitors include standard",
    ],
    coolFeatures: [
      "Perfect 50/50 weight distribution for sports car handling",
      "M Technic Sport differential for track-level cornering",
      "Drift Analyzer in M Mode tracks your performance",
    ],
    colors: ["Alpine White", "Jet Black", "Portimao Blue", "Dravit Grey", "Brooklyn Grey", "Tanzanite Blue"],
  },
  {
    id: "rivian-r1t-2024",
    brand: "Rivian",
    model: "R1T",
    year: 2024,
    bodyStyle: "truck",
    fuelType: "electric",
    basePrice: 69900,
    maxPrice: 99900,
    image: "https://images.unsplash.com/photo-1689702302312-8ef703f0d1d5?w=800&q=80",
    tagline: "The electric adventure truck that redefined the segment",
    description:
      "The Rivian R1T is the first dedicated electric pickup truck built from the ground up. With a unique gear tunnel, massive performance, and genuine off-road capability, the R1T proves electric trucks can be more capable than their gas counterparts.",
    specs: {
      horsepower: 835,
      torque: 908,
      engine: "Quad-Motor Electric",
      transmission: "Direct Drive",
      driveType: "AWD",
      zeroToSixty: 3.0,
      topSpeed: 110,
      electricRange: 410,
      totalRange: 410,
      batteryCapacity: 149,
      chargingTime: "25 min (140 mi, DC Fast Charge)",
      cargo: 52.3,
      seating: 5,
      towingCapacity: 11000,
      payloadCapacity: 1760,
    },
    trimLevels: [
      { name: "Standard", price: 69900, highlights: ["Standard Pack", "270+ mi range", "Dual Motor"] },
      { name: "Adventure", price: 79900, highlights: ["Max Pack", "410 mi range", "Quad Motor"] },
      { name: "Launch Edition", price: 99900, highlights: ["All features", "Exclusive colors", "Max tow pkg"] },
    ],
    safety: {
      rating: "5-Star Overall",
      ratingSource: "NHTSA 2024",
      features: [
        "Driver+ Assistance System",
        "Forward Collision Warning",
        "Automatic Emergency Braking",
        "Adaptive Cruise Control",
        "Lane Keeping Assist",
        "Blind Spot Detection",
        "360-degree cameras",
        "Surround sound alerts",
      ],
    },
    interiorFeatures: [
      "15.6-inch touchscreen",
      "6.8-inch driver display",
      "Heated and ventilated front/rear seats",
      "Panoramic glass roof",
      "Premium Meridian audio (14 speakers)",
      "Camp Speaker (removable Bluetooth speaker)",
      "Interior ambient lighting",
    ],
    exteriorFeatures: [
      "Gear Tunnel storage compartment",
      "Camp Kitchen slide-out cooking setup (optional)",
      "Removable side steps",
      "Cargo bed with multiple 120V outlets",
      "Integrated bed cover",
      "Vehicle Horn (multi-sound)",
    ],
    techFeatures: [
      "Rivian OS with OTA updates",
      "Amazon Alexa built-in",
      "Wireless Apple CarPlay / Android Auto",
      "Adventure Network fast charging",
      "V2H (vehicle-to-home) capability",
      "Off-road modes (Mud, Sand, Rock, Rally)",
      "Air compressor built-in",
    ],
    pros: [
      "Unmatched performance (0-60 in 3.0 seconds in a truck)",
      "Genius Gear Tunnel is incredibly practical",
      "Genuine off-road capability with air suspension",
      "Built-in air compressor for tires",
      "Frunk + gear tunnel + bed = maximum storage",
    ],
    cons: [
      "Very expensive compared to gas trucks",
      "Charging network smaller than Tesla's",
      "Range decreases significantly when towing",
      "Company still establishing long-term reliability record",
    ],
    coolFeatures: [
      "Gear Tunnel: waterproof, lockable pass-through storage under the bed",
      "Camp Kitchen: a full slide-out kitchen with a stove and sink (optional add-on)",
      "Tank Turn: quad motors can rotate the truck nearly in place",
    ],
    colors: ["Limestone", "Forest Green", "El Cap Granite", "Midnight", "Glacier White", "Red Canyon"],
  },
  {
    id: "hyundai-ioniq5-2024",
    brand: "Hyundai",
    model: "IONIQ 5",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "electric",
    basePrice: 41450,
    maxPrice: 56500,
    image: "https://images.unsplash.com/photo-1647418552401-f3958302b72a?w=800&q=80",
    tagline: "Retro-futuristic design meets ultra-fast charging",
    description:
      "The Hyundai IONIQ 5 turns heads with its pixel-art inspired retro design and delivers on substance with 800V ultra-fast charging (5 min = 68 miles), a spacious lounge-like interior, and Vehicle-to-Load capability.",
    specs: {
      horsepower: 320,
      torque: 446,
      engine: "Dual Motor Electric",
      transmission: "Direct Drive",
      driveType: "AWD",
      zeroToSixty: 5.1,
      topSpeed: 115,
      electricRange: 266,
      totalRange: 266,
      batteryCapacity: 77.4,
      chargingTime: "18 min (10-80%, 800V ultra-fast)",
      cargo: 27.2,
      seating: 5,
    },
    trimLevels: [
      { name: "Standard Range RWD", price: 41450, highlights: ["58kWh battery", "220 mi range", "RWD"] },
      { name: "Long Range RWD", price: 46450, highlights: ["77.4kWh battery", "303 mi range", "RWD"] },
      { name: "Long Range AWD", price: 49450, highlights: ["AWD", "266 mi range", "320hp"] },
      { name: "SE Standard Range", price: 43950, highlights: ["Sunroof", "Digital mirrors option"] },
      { name: "Limited AWD", price: 56500, highlights: ["Relaxation seats", "Digital side mirrors", "Panoramic roof"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Hyundai SmartSense",
        "Forward Collision Avoidance",
        "Lane Keeping Assist",
        "Blind-Spot Collision Warning",
        "Rear Cross-Traffic Collision Warning",
        "Highway Driving Assist 2",
        "Surround View Monitor",
      ],
    },
    interiorFeatures: [
      "Sliding center console (moves 5.5 inches)",
      "Reclining rear seats",
      "12-inch touchscreen + 12-inch driver display",
      "Relaxation Front Seats (Limited)",
      "Heated and ventilated front seats",
      "Panoramic sunroof",
      "Flat floor (no transmission tunnel)",
    ],
    exteriorFeatures: [
      "Pixel LED headlights and taillights",
      "Flush door handles",
      "20-inch wheels",
      "Retractable door handles",
      "Frunk storage compartment",
      "Parametric pixel design language",
    ],
    techFeatures: [
      "800V ultra-fast charging architecture",
      "Vehicle-to-Load (V2L) up to 3.6kW",
      "Wireless Apple CarPlay / Android Auto",
      "BlueLink connected services",
      "OTA software updates",
      "Digital side mirrors (optional)",
      "Augmented Reality navigation",
    ],
    pros: [
      "800V charging is class-leading (fastest charging speed)",
      "Vehicle-to-Load powers appliances anywhere",
      "Spacious, lounge-like interior with sliding console",
      "Outstanding design — genuinely head-turning",
      "Excellent 5-year warranty coverage",
    ],
    cons: [
      "Range trails some competitors",
      "Charging network smaller than Tesla",
      "Digital side mirrors hard to read in bright light",
      "Cargo space behind rear seats is modest",
    ],
    coolFeatures: [
      "Vehicle-to-Load: power a campsite, charge other devices, or run appliances with your car",
      "800V architecture: charges faster than almost any other EV on the market",
      "Sliding center console creates a walk-through cabin feel",
    ],
    colors: ["Atlas White", "Lucid Blue", "Gravity Gold", "Mystic Olive", "Digital Teal", "Phantom Black"],
  },
  {
    id: "chevrolet-corvette-2024",
    brand: "Chevrolet",
    model: "Corvette",
    year: 2024,
    bodyStyle: "coupe",
    fuelType: "gasoline",
    basePrice: 67295,
    maxPrice: 135000,
    image: "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=800&q=80",
    tagline: "Mid-engine American supercar — starting under $70k",
    description:
      "The C8 Corvette remains America's supercar story: mid-engine layout, naturally aspirated V8, and genuine 911-fighting performance at a fraction of European rival costs. With the optional Z51 package, it decimates cars costing twice as much.",
    specs: {
      horsepower: 495,
      torque: 470,
      engine: "6.2L Naturally Aspirated LT2 V8",
      transmission: "8-Speed Dual-Clutch",
      driveType: "RWD",
      zeroToSixty: 2.9,
      topSpeed: 194,
      mpgCity: 15,
      mpgHighway: 27,
      mpgCombined: 19,
      cargo: 12.6,
      seating: 2,
    },
    trimLevels: [
      { name: "1LT", price: 67295, highlights: ["495hp V8", "Base features", "Magnetic Ride"] },
      { name: "2LT", price: 73295, highlights: ["GT2 seats", "Heads-up display", "Bose audio"] },
      { name: "3LT", price: 78295, highlights: ["Full leather", "Carbon fiber accents", "Front lift"] },
      { name: "Z06", price: 110295, highlights: ["670hp flat-plane V8", "0-60 in 2.6s", "Track-ready"] },
      { name: "Z06 Z07", price: 135000, highlights: ["Carbon ceramic brakes", "Carbon aero package", "Extreme grip"] },
    ],
    safety: {
      rating: "4-Star Overall",
      ratingSource: "NHTSA 2024",
      features: [
        "Forward Collision Alert",
        "Lane Change Alert with Side Blind Zone Alert",
        "Rear Park Assist",
        "Rear Camera Mirror",
        "Performance Data Recorder",
        "Head-Up Display",
      ],
    },
    interiorFeatures: [
      "12-inch diagonal infotainment screen",
      "8-inch driver info display",
      "GT2 bucket seats (optional)",
      "Carbon fiber trim options",
      "Bose Performance sound system",
      "Head-up display",
      "Interior mood lighting",
    ],
    exteriorFeatures: [
      "Mid-engine design with dramatic proportions",
      "Removable targa roof panel",
      "Visible rear engine through glass",
      "Quad exhaust",
      "Front lift system (optional)",
      "Carbon fiber aero options",
    ],
    techFeatures: [
      "Performance Data Recorder (onboard lap timer)",
      "Wireless Apple CarPlay / Android Auto",
      "MyChevrolet mobile app",
      "Magnetic Ride Control 4.0",
      "Track Mode / Wet Mode",
      "Launch Control",
      "Z-Mode (customizable performance settings)",
    ],
    pros: [
      "Supercar performance at a reasonable starting price",
      "Naturally aspirated V8 sound is extraordinary",
      "Mid-engine handling is exceptional",
      "Practical for a supercar (frunk + rear trunk)",
      "Available in coupe and convertible",
    ],
    cons: [
      "Only seats 2",
      "Dealer markups can be significant",
      "Long options list to get basic features",
      "Fuel economy is poor in city driving",
    ],
    coolFeatures: [
      "Performance Data Recorder: built-in video recording of your laps",
      "Visible engine through the rear glass — the V8 is part of the show",
      "Front lift system raises the nose to clear speed bumps and driveways",
    ],
    colors: ["Arctic White", "Elkhart Lake Blue", "Accelerate Yellow", "Amplify Orange Tintcoat", "Red Mist", "Black"],
  },
  {
    id: "subaru-outback-2024",
    brand: "Subaru",
    model: "Outback",
    year: 2024,
    bodyStyle: "wagon",
    fuelType: "gasoline",
    basePrice: 28995,
    maxPrice: 45645,
    image: "https://images.unsplash.com/photo-1609772168547-d216c44c3f85?w=800&q=80",
    tagline: "Adventure-ready wagon with standard AWD",
    description:
      "The Subaru Outback invented the crossover wagon category and remains its best example. Standard Symmetrical AWD, 8.7 inches of ground clearance, and exceptional off-road capability combined with car-like fuel economy and practicality make it uniquely capable.",
    specs: {
      horsepower: 182,
      torque: 176,
      engine: "2.5L Boxer 4-Cylinder",
      transmission: "Lineartronic CVT",
      driveType: "AWD",
      zeroToSixty: 8.5,
      topSpeed: 119,
      mpgCity: 26,
      mpgHighway: 33,
      mpgCombined: 29,
      cargo: 75.7,
      seating: 5,
      towingCapacity: 3500,
    },
    trimLevels: [
      { name: "Base", price: 28995, highlights: ["Standard AWD", "EyeSight", "8-inch screen"] },
      { name: "Premium", price: 32195, highlights: ["Moonroof", "Power rear gate", "Heated seats"] },
      { name: "Limited", price: 37295, highlights: ["Leather", "Navi", "Harman Kardon audio"] },
      { name: "Touring", price: 41295, highlights: ["XT turbo engine", "Premium everything", "Starlink"] },
      { name: "Wilderness", price: 45645, highlights: ["9.5-inch clearance", "All-terrain tires", "Special AWD"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "EyeSight Driver Assist (standard)",
        "Pre-Collision Braking",
        "Adaptive Cruise Control",
        "Lane Keep Assist",
        "Lane Departure Warning",
        "Rear Cross-Traffic Braking",
        "Reverse Automatic Braking",
      ],
    },
    interiorFeatures: [
      "11.6-inch portrait touchscreen (Limited+)",
      "Heated front and rear seats (Limited+)",
      "Power rear gate",
      "Starlink Safety Plus",
      "Panoramic moonroof (Premium+)",
      "Power driver seat",
      "Wireless charging",
    ],
    exteriorFeatures: [
      "Body cladding for trail protection",
      "Roof rails (standard)",
      "8.7-inch ground clearance (9.5-inch Wilderness)",
      "Integrated trailer hitch",
      "LED headlights",
      "X-MODE off-road system",
    ],
    techFeatures: [
      "Subaru StarLink multimedia",
      "Wireless Apple CarPlay / Android Auto",
      "EyeSight with DriverFocus",
      "Subaru STARLINK Safety services",
      "Connected services with remote start",
      "SiriusXM Guardian",
    ],
    pros: [
      "Standard AWD on every trim — no extra cost",
      "Best-in-class ground clearance for the segment",
      "Massive cargo capacity",
      "EyeSight is one of the best driver assistance suites",
      "Excellent reliability and resale value",
    ],
    cons: [
      "Base engine is slow by modern standards",
      "CVT transmission can feel uninspiring",
      "Interior materials feel budget in base trims",
      "Turbo engine has higher fuel costs",
    ],
    coolFeatures: [
      "X-MODE with Snow/Dirt and Deep Snow/Mud modes — genuine off-road capability",
      "Wilderness trim gets 9.5 inches of clearance and locking rear differential",
      "Boxer engine sits low for better center of gravity vs. inline engines",
    ],
    colors: ["Crystal White Pearl", "Magnetite Gray", "Wilderness Green", "Geyser Blue", "Autumn Green", "Solar Orange"],
  },
  {
    id: "porsche-taycan-2024",
    brand: "Porsche",
    model: "Taycan",
    year: 2024,
    bodyStyle: "sedan",
    fuelType: "electric",
    basePrice: 93300,
    maxPrice: 185000,
    image: "https://images.unsplash.com/photo-1584060622420-0673aad46076?w=800&q=80",
    tagline: "Electric performance that doesn't compromise the Porsche DNA",
    description:
      "The Porsche Taycan redefined what an electric performance car can be. With 800V charging, authentic sports car handling and feel, and a stunning interior, the Taycan proves EVs can excite, not just transport.",
    specs: {
      horsepower: 670,
      torque: 626,
      engine: "Dual Motor Electric (Turbo S)",
      transmission: "2-Speed PDK",
      driveType: "AWD",
      zeroToSixty: 2.4,
      topSpeed: 161,
      electricRange: 246,
      totalRange: 246,
      batteryCapacity: 93.4,
      chargingTime: "22 min (5-80%, 800V)",
      cargo: 14.3,
      seating: 4,
    },
    trimLevels: [
      { name: "Taycan", price: 93300, highlights: ["408hp", "273 mi range", "RWD"] },
      { name: "4S", price: 113000, highlights: ["AWD", "563hp", "Advanced charging"] },
      { name: "GTS", price: 136000, highlights: ["590hp", "Sport Chrono", "Alcantara"] },
      { name: "Turbo", price: 157000, highlights: ["670hp", "0-60 in 2.6s"] },
      { name: "Turbo S", price: 185000, highlights: ["760hp", "0-60 in 2.4s", "Carbon ceramic brakes"] },
    ],
    safety: {
      rating: "5-Star Overall",
      ratingSource: "Euro NCAP 2024",
      features: [
        "Porsche InnoDrive (ACC with navigation)",
        "Lane Keeping Assist",
        "Rear Cross-Traffic Alert",
        "Night Vision Assist (optional)",
        "Surround View",
        "Park Assist with sensors and camera",
        "Emergency Assist",
      ],
    },
    interiorFeatures: [
      "Curved 16.8-inch infotainment display",
      "Passenger display (optional)",
      "Sport Chrono Package",
      "18-way adaptive sport seats",
      "Bose or Burmester audio",
      "Ambient lighting",
      "Genuine leather and Alcantara",
    ],
    exteriorFeatures: [
      "Porsche Active Aerodynamics (PAA)",
      "Adaptive rear spoiler",
      "20-inch alloy wheels (standard)",
      "4-point LED headlights",
      "Matrix LED headlights (optional)",
      "Air suspension",
    ],
    techFeatures: [
      "Porsche Communication Management (PCM)",
      "Wireless Apple CarPlay",
      "OTA software updates",
      "800V ultra-fast charging",
      "Porsche Charging Service",
      "Launch Control",
      "Porsche Track Precision App",
    ],
    pros: [
      "Best driving dynamics of any electric car",
      "800V charging — very fast charge times",
      "Stunning interior quality and technology",
      "Genuine sports car performance",
      "2-speed transmission provides realistic 'gearshift' feel",
    ],
    cons: [
      "Very expensive — features add up quickly",
      "Rear seat space is limited",
      "Range trails Tesla Model S",
      "Porsche options list can double the base price",
    ],
    coolFeatures: [
      "2-Speed transmission in an EV for authentic performance feel",
      "800V architecture: fastest possible charging for production EVs",
      "Porsche Track Precision App records performance data on track days",
    ],
    colors: ["Frozen Blue Metallic", "Chalk", "Gentian Blue", "Carmine Red", "Mamba Green", "Dolomite Silver"],
  },
  {
    id: "jeep-wrangler-2024",
    brand: "Jeep",
    model: "Wrangler",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "plug-in hybrid",
    basePrice: 33395,
    maxPrice: 61000,
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?w=800&q=80",
    tagline: "The original off-roader, now with plug-in power",
    description:
      "The Jeep Wrangler 4xe PHEV combines Jeep's legendary off-road DNA with a plug-in hybrid powertrain delivering 25 miles of electric range. It remains the go-anywhere benchmark while offering daily EV commuting efficiency.",
    specs: {
      horsepower: 375,
      torque: 470,
      engine: "2.0L Turbo 4-Cylinder PHEV",
      transmission: "8-Speed Automatic",
      driveType: "4WD",
      zeroToSixty: 6.0,
      topSpeed: 100,
      mpgCity: 20,
      mpgHighway: 24,
      mpgCombined: 22,
      electricRange: 25,
      totalRange: 370,
      batteryCapacity: 17,
      chargingTime: "2 hours (Level 2)",
      cargo: 72.4,
      seating: 5,
    },
    trimLevels: [
      { name: "Sport", price: 33395, highlights: ["Dana 30/35 axles", "3.73 gears", "Steel bumpers"] },
      { name: "Sahara", price: 45000, highlights: ["Body-colored fenders", "Heated seats", "Navi"] },
      { name: "Rubicon", price: 53000, highlights: ["Dana 44 axles", "4:1 transfer case", "Lockers"] },
      { name: "Rubicon 392", price: 61000, highlights: ["392hp V8", "0-60 in 4.5s", "Rock-Rails"] },
    ],
    safety: {
      rating: "4-Star Overall",
      ratingSource: "NHTSA 2024",
      features: [
        "Forward Collision Warning",
        "Automatic Emergency Braking",
        "ParkSense Rear Park Assist",
        "Blind-Spot Monitoring",
        "Rear Cross-Path Detection",
        "Tire Fill Alert",
      ],
    },
    interiorFeatures: [
      "8.4 or 12-inch Uconnect touchscreen",
      "Removable doors and roof",
      "Fold-down windshield",
      "Heated front seats",
      "Alpine Premium Audio",
      "All-weather floor mats",
      "Grab handles throughout",
    ],
    exteriorFeatures: [
      "Removable doors (tool-free)",
      "Removable roof panels",
      "Fold-down windshield",
      "Round headlights (iconic design)",
      "Rock rails (Rubicon)",
      "Steel bumpers",
      "Skid plates",
    ],
    techFeatures: [
      "Uconnect 5 with 12-inch screen",
      "Wireless Apple CarPlay / Android Auto",
      "Off-Road Pages (trail info display)",
      "Selec-Terrain system",
      "Rock-Trac 4WD (Rubicon)",
      "Trail Rated capability",
    ],
    pros: [
      "Unmatched off-road capability (especially Rubicon)",
      "Completely open-air experience is unique",
      "PHEV 4xe gets EV range for daily commutes",
      "Cult following and strong community",
      "Excellent resale value",
    ],
    cons: [
      "Poor on-road ride and handling",
      "High wind and road noise",
      "Limited tech compared to modern SUVs",
      "Poor fuel economy in gas-only mode",
    ],
    coolFeatures: [
      "Remove all 4 doors and the roof in minutes for true open-air driving",
      "Fold-down windshield for total wind-in-face experience",
      "Silent 4xe EV mode for stealthy trail running at night",
    ],
    colors: ["Bright White", "Black", "Firecracker Red", "Hydro Blue", "Sarge Green", "Sting-Gray"],
  },
  {
    id: "kia-ev6-2024",
    brand: "Kia",
    model: "EV6",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "electric",
    basePrice: 42600,
    maxPrice: 61900,
    image: "https://images.unsplash.com/photo-1665127771643-0bc02014da61?w=800&q=80",
    tagline: "The EV that wants to be a sports car",
    description:
      "The Kia EV6 GT-Line packs genuine excitement into an everyday crossover shape. With the GT variant hitting 0-60 in 3.4 seconds, 800V ultra-fast charging, and a dramatic design, the EV6 offers Tesla-rivaling performance at a lower price.",
    specs: {
      horsepower: 576,
      torque: 545,
      engine: "Dual Motor Electric (GT)",
      transmission: "Direct Drive",
      driveType: "AWD",
      zeroToSixty: 3.4,
      topSpeed: 161,
      electricRange: 310,
      totalRange: 310,
      batteryCapacity: 77.4,
      chargingTime: "18 min (10-80%)",
      cargo: 24.4,
      seating: 5,
    },
    trimLevels: [
      { name: "Light Standard Range", price: 42600, highlights: ["53kWh", "232 mi range", "RWD"] },
      { name: "Wind Long Range", price: 47600, highlights: ["77.4kWh", "310 mi range", "RWD"] },
      { name: "GT-Line AWD", price: 50500, highlights: ["AWD", "266 mi", "Sport appearance"] },
      { name: "GT", price: 61900, highlights: ["576hp", "0-60 in 3.4s", "Drift mode"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Kia DriveWise",
        "Forward Collision Avoidance",
        "Lane Keep Assist 2",
        "Blind Spot Collision Warning",
        "Rear Cross-Traffic Collision Avoidance",
        "Highway Driving Assist 2",
        "Surround View Monitor",
      ],
    },
    interiorFeatures: [
      "Dual panoramic 12-inch screens",
      "Heated and ventilated front seats",
      "Heated rear seats",
      "Meridian premium audio",
      "Panoramic sunroof",
      "Flat floor design",
      "Vehicle-to-Load (V2L) up to 3.6kW",
    ],
    exteriorFeatures: [
      "Shooting brake silhouette design",
      "Flush door handles",
      "Sequential LED turn signals",
      "20-inch aerodynamic wheels",
      "Unique rear wing spoiler",
    ],
    techFeatures: [
      "800V ultra-fast charging",
      "Vehicle-to-Load (V2L)",
      "Wireless Apple CarPlay / Android Auto",
      "OTA updates",
      "GT Drift Mode",
      "e-ASD Active Sound Design",
      "Augmented Reality HUD",
    ],
    pros: [
      "GT variant is a genuine performance car",
      "800V fast charging on all variants",
      "Outstanding design inside and out",
      "Vehicle-to-Load is practical for camping",
      "7-year/70,000-mile warranty",
    ],
    cons: [
      "Rear seat headroom is tight for taller passengers",
      "Cargo space trails class leaders",
      "GT variant has reduced range vs. standard",
      "Charging network smaller than Tesla",
    ],
    coolFeatures: [
      "Drift Mode on the GT: actively controls torque split for controlled oversteer",
      "800V charging: add 68 miles in just 4.5 minutes",
      "e-ASD: synthesizes a sporty sound inside the cabin based on speed and throttle",
    ],
    colors: ["Snow White Pearl", "Runway Red", "Midnight Black Pearl", "Interstellar Gray", "Glacier", "Yacht Blue"],
  },
  {
    id: "mercedes-gle-2024",
    brand: "Mercedes-Benz",
    model: "GLE",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "hybrid",
    basePrice: 62150,
    maxPrice: 89900,
    image: "https://images.unsplash.com/photo-1611168935847-4bf3f7291cde?w=800&q=80",
    tagline: "Luxury redefined — the flagship mid-size SUV",
    description:
      "The Mercedes-Benz GLE sets the benchmark for luxury mid-size SUVs. With the MBUX infotainment system, optional E-Active Body Control magic carpet ride, and a refined interior rivaling sedans costing twice as much, the GLE is the ultimate family hauler.",
    specs: {
      horsepower: 429,
      torque: 384,
      engine: "3.0L Turbo I6 48V Mild Hybrid",
      transmission: "9G-TRONIC Automatic",
      driveType: "AWD",
      zeroToSixty: 5.3,
      topSpeed: 155,
      mpgCity: 21,
      mpgHighway: 26,
      mpgCombined: 23,
      cargo: 74.9,
      seating: 7,
    },
    trimLevels: [
      { name: "GLE 350", price: 62150, highlights: ["255hp turbo-4", "AWD", "MBUX"] },
      { name: "GLE 450", price: 72500, highlights: ["375hp inline-6", "AMG Line", "Third row"] },
      { name: "GLE 580", price: 82000, highlights: ["510hp V8", "E-Active Body Control"] },
      { name: "AMG GLE 63S", price: 89900, highlights: ["603hp V8", "0-60 in 3.8s", "AMG Track Pace"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK",
      ratingSource: "IIHS 2024",
      features: [
        "Active Brake Assist",
        "Active Lane Keeping Assist",
        "Active Blind Spot Assist",
        "PRE-SAFE Sound",
        "Active Distance Assist DISTRONIC",
        "360-degree camera",
        "Traffic Sign Assist",
      ],
    },
    interiorFeatures: [
      "MBUX 12.3-inch infotainment + 12.3-inch digital cluster",
      "Optional third-row seating",
      "Burmester 3D surround sound (optional)",
      "Energizing Comfort system",
      "Nappa leather upholstery",
      "Heated and ventilated front seats",
      "Ambient lighting (64 colors)",
    ],
    exteriorFeatures: [
      "Air suspension (standard on 450+)",
      "Adaptive highbeam assist",
      "Running boards",
      "Power tailgate with hands-free",
      "Panoramic sunroof",
      "Chrome trim accents",
    ],
    techFeatures: [
      "MBUX with 'Hey Mercedes' voice assistant",
      "Wireless Apple CarPlay / Android Auto",
      "MBUX Augmented Reality Navigation",
      "E-Active Body Control (optional) — reads road surface",
      "OTA updates",
      "Mercedes me connect app",
      "Transparent Hood (off-road camera view)",
    ],
    pros: [
      "Exceptionally refined and quiet ride",
      "Optional third row for a 7-seater luxury SUV",
      "MBUX is one of the best infotainment systems available",
      "E-Active Body Control provides magic carpet ride quality",
      "Prestigious brand and strong resale value",
    ],
    cons: [
      "Very expensive when optioned up",
      "Third row is best for children only",
      "Infotainment can overwhelm with too many options",
      "Running costs are high",
    ],
    coolFeatures: [
      "E-Active Body Control uses stereo cameras to pre-scan the road and adjust each shock absorber individually before hitting a bump",
      "MBUX Augmented Reality Navigation overlays directions on a live camera feed",
      "Energizing Comfort system syncs climate, massage seats, lighting, and music for a wellness experience",
    ],
    colors: ["Obsidian Black Metallic", "Polar White", "Selenite Grey", "Brilliant Blue", "Mojave Silver", "Emerald Green"],
  },
  {
    id: "toyota-rav4prime-2024",
    brand: "Toyota",
    model: "RAV4 Prime",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "plug-in hybrid",
    basePrice: 43790,
    maxPrice: 51610,
    image: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80",
    tagline: "The practical PHEV SUV that does everything right",
    description:
      "The Toyota RAV4 Prime is the perfect everyday SUV: 42 miles of EV range handles most commutes, then the 302hp combined system takes over for long trips. With standard AWD-e and Toyota's reliability, it's the most sensible plug-in on the market.",
    specs: {
      horsepower: 302,
      torque: 302,
      engine: "2.5L 4-Cyl PHEV + 2 Electric Motors",
      transmission: "E-CVT",
      driveType: "AWD",
      zeroToSixty: 5.7,
      topSpeed: 112,
      mpgCity: 38,
      mpgHighway: 35,
      mpgCombined: 38,
      electricRange: 42,
      totalRange: 600,
      batteryCapacity: 18.1,
      chargingTime: "4.5 hours (Level 2)",
      cargo: 37.6,
      seating: 5,
    },
    trimLevels: [
      { name: "SE", price: 43790, highlights: ["302hp", "42 mi EV range", "AWD-e"] },
      { name: "XSE", price: 47290, highlights: ["Panoramic moonroof", "Heated seats", "JBL audio"] },
      { name: "XSE Premium", price: 51610, highlights: ["Wireless charging", "Ventilated seats", "12.3-inch screen"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Toyota Safety Sense 2.0",
        "Pre-Collision System",
        "Adaptive Cruise Control",
        "Lane Departure Alert",
        "Automatic High Beams",
        "Rear Cross-Traffic Alert",
        "Blind Spot Monitor",
      ],
    },
    interiorFeatures: [
      "10.5-inch touchscreen",
      "Heated front seats",
      "Panoramic moonroof (XSE+)",
      "JBL Premium Audio (XSE+)",
      "Wireless charging (XSE Premium)",
      "Ventilated front seats (XSE Premium)",
      "Power tailgate",
    ],
    exteriorFeatures: [
      "LED headlights",
      "Two-tone paint options",
      "18-inch alloy wheels",
      "Roof rails",
      "Power tailgate",
      "Unique PHEV badging",
    ],
    techFeatures: [
      "Toyota Audio Multimedia",
      "Wireless Apple CarPlay",
      "Wireless Android Auto",
      "Toyota Connected Services",
      "Remote charging start",
      "EV/HV/Auto mode selector",
      "OTA updates",
    ],
    pros: [
      "42-mile EV range covers most daily commutes",
      "600+ miles total range eliminates range anxiety",
      "302hp is surprisingly quick for a family SUV",
      "Toyota reliability with excellent warranty",
      "Federal tax credit eligible",
    ],
    cons: [
      "Limited availability — often sold above MSRP",
      "Interior is not as premium as German rivals",
      "Charging time longer than some competitors",
      "No third-row option",
    ],
    coolFeatures: [
      "EV Mode Lock: reserve battery charge for city driving later on a road trip",
      "Surprisingly quick 0-60 mph for a family SUV",
      "Standard AWD-e provides confident all-weather traction",
    ],
    colors: ["Wind Chill Pearl", "Blueprint", "Cavalry Blue", "Midnight Black", "Magnetic Gray", "Super White"],
  },
  {
    id: "lucid-air-2024",
    brand: "Lucid",
    model: "Air",
    year: 2024,
    bodyStyle: "sedan",
    fuelType: "electric",
    basePrice: 69900,
    maxPrice: 249000,
    image: "https://images.unsplash.com/photo-1740001574335-cd22a1313186?w=800&q=80",
    tagline: "The longest range, fastest charging EV ever built",
    description:
      "The Lucid Air Pure starts under $70k but the Dream Edition at 1,234hp makes it the world's most powerful production sedan. The Grand Touring holds the EV range record at 516 miles on a single charge, demonstrating Lucid's engineering excellence.",
    specs: {
      horsepower: 1234,
      torque: 1025,
      engine: "Dual Motor Electric (Dream Edition)",
      transmission: "Direct Drive",
      driveType: "AWD",
      zeroToSixty: 1.89,
      topSpeed: 168,
      electricRange: 516,
      totalRange: 516,
      batteryCapacity: 118,
      chargingTime: "22 min (300 mi added)",
      cargo: 10,
      seating: 5,
    },
    trimLevels: [
      { name: "Air Pure", price: 69900, highlights: ["410hp", "410 mi range", "RWD"] },
      { name: "Air Touring", price: 95000, highlights: ["620hp", "425 mi range", "AWD"] },
      { name: "Grand Touring", price: 138000, highlights: ["819hp", "516 mi range", "AWD"] },
      { name: "Sapphire", price: 249000, highlights: ["1234hp", "0-60 in 1.89s", "3 motors"] },
    ],
    safety: {
      rating: "5-Star Overall",
      ratingSource: "NHTSA 2024",
      features: [
        "DreamDrive Pro (standard)",
        "Automatic Emergency Braking",
        "Lane Departure Warning",
        "Adaptive Cruise Control",
        "Blind Spot Warning",
        "Front and Rear Park Sensors",
        "360-degree camera",
      ],
    },
    interiorFeatures: [
      "34-inch curved Glass Cockpit",
      "Dolby Atmos spatial audio (21 speakers)",
      "Executive seating with ottoman rear seats (Grand Touring+)",
      "Nappa leather throughout",
      "Curved micro-pillar canopy roof",
      "Ambient lighting",
      "Heated and ventilated seats",
    ],
    exteriorFeatures: [
      "Frameless door glass",
      "Ultra-low drag coefficient (0.197 Cd)",
      "21-inch forged aluminum wheels",
      "Unique pillar-free design",
      "Flush door handles",
      "Rear-hinged rear doors (optional)",
    ],
    techFeatures: [
      "34-inch UHD display",
      "Amazon Alexa built-in",
      "Wireless Apple CarPlay",
      "DreamDrive Pro ADAS",
      "WARP Charging (up to 300 miles in 22 min)",
      "OTA updates",
      "Dolby Atmos spatial audio",
    ],
    pros: [
      "World record range: 516 miles EPA-rated",
      "Fastest charging among non-800V cars",
      "1,234hp in Sapphire trim — fastest production sedan ever",
      "Spacious, aircraft-inspired interior",
      "American-made luxury EV challenger",
    ],
    cons: [
      "Brand is young with limited service network",
      "No third-row option",
      "Software still catching up to Tesla",
      "Limited charging network vs. Tesla",
    ],
    coolFeatures: [
      "516 miles of range — no other EV comes close in a sedan form factor",
      "WARP Charging: adds 300 miles in 22 minutes",
      "Sapphire's 1,234hp makes it the quickest production sedan on earth",
    ],
    colors: ["Stellar White", "Infinite Black", "Zenith Red", "Cosmos Silver", "Quantum Grey", "Eureka Gold"],
  },

  // ─── NEW CARS ────────────────────────────────────────────────────────────────

  {
    id: "honda-civic-2024",
    brand: "Honda",
    model: "Civic",
    year: 2024,
    bodyStyle: "sedan",
    fuelType: "gasoline",
    basePrice: 24950,
    maxPrice: 32650,
    image: "https://images.unsplash.com/photo-1594070319944-7c0cbebb6f58?w=800&q=80",
    tagline: "The benchmark compact sedan — sporty, reliable, affordable",
    description:
      "The 2024 Honda Civic continues to set the standard for compact cars with a sharp design, responsive handling, and a feature-rich interior that punches well above its price class. Whether you commute or carve backroads, the Civic delivers.",
    specs: {
      horsepower: 158,
      torque: 138,
      engine: "1.5L Turbocharged 4-Cylinder",
      transmission: "CVT",
      driveType: "FWD",
      zeroToSixty: 7.5,
      topSpeed: 134,
      mpgCity: 31,
      mpgHighway: 40,
      mpgCombined: 35,
      cargo: 14.8,
      seating: 5,
    },
    trimLevels: [
      { name: "LX", price: 24950, highlights: ["Honda Sensing suite", "7-inch display", "Backup camera"] },
      { name: "Sport", price: 26850, highlights: ["18-inch wheels", "Sport grille", "Wireless CarPlay"] },
      { name: "EX", price: 28450, highlights: ["Sunroof", "Heated seats", "Remote start"] },
      { name: "Touring", price: 32650, highlights: ["12-inch touchscreen", "Bose audio", "LED headlights"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Honda Sensing Standard",
        "Collision Mitigation Braking",
        "Adaptive Cruise Control",
        "Lane Keeping Assist",
        "Road Departure Mitigation",
        "Blind Spot Information System",
        "Rear Cross Traffic Monitor",
      ],
    },
    interiorFeatures: [
      "9-inch Honda Connect display (EX+)",
      "Wireless Apple CarPlay & Android Auto",
      "Heated front seats",
      "Dual-zone climate control",
      "USB-C and USB-A ports",
      "60/40 split rear seat",
    ],
    exteriorFeatures: [
      "Full LED lighting",
      "16-inch alloy wheels",
      "Chrome exterior accents",
      "Power moonroof (EX+)",
    ],
    techFeatures: [
      "Google built-in (Touring)",
      "Wi-Fi Hotspot capability",
      "Digital instrument cluster",
      "Wireless charging (EX+)",
    ],
    pros: [
      "Excellent fuel economy for a non-hybrid",
      "Spacious interior for the class",
      "Honda reliability reputation",
      "Engaging driving dynamics",
      "Strong resale value",
    ],
    cons: [
      "No hybrid option (unlike Camry)",
      "Base LX lacks wireless CarPlay",
      "Firm ride on Sport trim",
    ],
    coolFeatures: [
      "Type R version hits 315 hp — one of the most powerful FWD cars ever",
      "Turbocharged engine feels peppier than numbers suggest",
      "One of the largest trunks in the compact class",
    ],
    colors: ["Sonic Gray Pearl", "Rallye Red", "Aegean Blue", "Lunar Silver", "Platinum White", "Meteoroid Gray"],
  },

  {
    id: "tesla-model-y-2024",
    brand: "Tesla",
    model: "Model Y",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "electric",
    basePrice: 43990,
    maxPrice: 58990,
    image: "https://images.unsplash.com/photo-1676754568744-7852efc67c40?w=800&q=80",
    tagline: "The world's best-selling EV — now even better",
    description:
      "The 2024 Tesla Model Y is the most popular vehicle on earth. With up to 330 miles of range, America's fastest-growing Supercharger network, and over-the-air updates that improve the car over time, it sets the bar for electric SUVs.",
    specs: {
      horsepower: 384,
      torque: 376,
      engine: "Dual Electric Motors",
      transmission: "Single-Speed Automatic",
      driveType: "AWD",
      zeroToSixty: 4.8,
      topSpeed: 135,
      electricRange: 330,
      totalRange: 330,
      batteryCapacity: 82,
      chargingTime: "~45 min (10–80% Supercharger)",
      cargo: 76,
      seating: 5,
    },
    trimLevels: [
      { name: "RWD", price: 43990, highlights: ["279 mi range", "Single motor", "18-inch Gemini wheels"] },
      { name: "Long Range AWD", price: 48990, highlights: ["330 mi range", "Dual motor", "Premium audio"] },
      { name: "Performance", price: 54990, highlights: ["3.5s 0-60", "20-inch wheels", "Track mode"] },
    ],
    safety: {
      rating: "5",
      ratingSource: "NHTSA 2024",
      features: [
        "Autopilot standard",
        "Automatic Emergency Braking",
        "Side Collision Warning",
        "Blind Spot Monitoring",
        "Lane Departure Avoidance",
        "8 airbags",
        "Sentry Mode (camera security)",
      ],
    },
    interiorFeatures: [
      "15.4-inch central touchscreen",
      "Heated front and rear seats",
      "Premium audio with 13 speakers",
      "Panoramic glass roof",
      "Vegan leather seating",
      "Wireless phone charging",
    ],
    exteriorFeatures: [
      "Flush door handles",
      "Full LED exterior lighting",
      "Powered liftgate",
      "18-inch or 20-inch wheels",
    ],
    techFeatures: [
      "Full Self-Driving capability (subscription)",
      "Over-the-air updates",
      "Tesla app remote control",
      "Bluetooth phone key",
      "Built-in dashcam & Sentry Mode",
    ],
    pros: [
      "World's best EV charging network (Supercharger)",
      "Industry-leading over-the-air updates",
      "Best-in-class safety ratings",
      "Spacious interior with frunk bonus storage",
      "Lowest operating cost of any SUV",
    ],
    cons: [
      "No physical controls for many functions",
      "Polarizing minimalist interior",
      "Build quality inconsistent across units",
      "Expensive FSD subscription",
    ],
    coolFeatures: [
      "Frunk (front trunk) adds hidden storage",
      "Bioweapon Defense Mode air filtration (Performance)",
      "Dog Mode & Camp Mode for pet owners and campers",
    ],
    colors: ["Pearl White", "Midnight Silver", "Deep Blue", "Solid Black", "Ultra Red", "Quicksilver"],
  },

  {
    id: "ford-mustang-2024",
    brand: "Ford",
    model: "Mustang",
    year: 2024,
    bodyStyle: "coupe",
    fuelType: "gasoline",
    basePrice: 32515,
    maxPrice: 60000,
    image: "https://images.unsplash.com/photo-1625231334168-35067f8853ed?w=800&q=80",
    tagline: "An American icon, completely reborn for 2024",
    description:
      "The all-new 7th generation Mustang debuts sharper styling, a new 5.0L V8 making 486 hp, a segment-first 12-inch digital cluster, and optional 10-speed automatic. It's the most driver-focused Mustang ever built.",
    specs: {
      horsepower: 486,
      torque: 418,
      engine: "5.0L V8 (GT)",
      transmission: "6-Speed Manual / 10-Speed Automatic",
      driveType: "RWD",
      zeroToSixty: 4.3,
      topSpeed: 160,
      mpgCity: 15,
      mpgHighway: 24,
      mpgCombined: 18,
      cargo: 13.5,
      seating: 4,
    },
    trimLevels: [
      { name: "EcoBoost", price: 32515, highlights: ["2.3L turbo 4-cyl", "315 hp", "Best fuel economy"] },
      { name: "GT", price: 42520, highlights: ["5.0L V8", "486 hp", "MagneRide available"] },
      { name: "GT Premium", price: 48000, highlights: ["12-inch digital cluster", "B&O audio", "Active valve exhaust"] },
      { name: "Dark Horse", price: 60000, highlights: ["500 hp", "Track-tuned suspension", "Brembo brakes"] },
    ],
    safety: {
      rating: "4",
      ratingSource: "NHTSA 2024",
      features: [
        "Pre-Collision Assist",
        "Automatic Emergency Braking",
        "Lane-Keeping System",
        "Blind Spot Information System",
        "Rear Cross-Traffic Alert",
        "Rear Backup Camera",
      ],
    },
    interiorFeatures: [
      "12.4-inch digital instrument cluster",
      "13.2-inch SYNC 4 touchscreen",
      "Heated and cooled front seats (Premium)",
      "Active noise control",
      "B&O Sound System (Premium)",
      "Wireless CarPlay & Android Auto",
    ],
    exteriorFeatures: [
      "Signature sequential turn signals",
      "LED projector headlights",
      "Dual exhaust with active valves",
      "19-inch machined-face wheels (GT)",
    ],
    techFeatures: [
      "SYNC 4 with voice control",
      "Launch Control (all trims)",
      "Rev Matching (manual)",
      "Customizable Drive Modes",
      "Ford Performance app integration",
    ],
    pros: [
      "Iconic styling reborn for a new generation",
      "5.0L V8 produces an intoxicating exhaust note",
      "Most affordable V8 sports car in America",
      "Wide range of trims from daily driver to track beast",
    ],
    cons: [
      "Rear visibility is limited",
      "Fuel economy is poor (V8)",
      "Only 4 seats",
      "Rear seat is cramped for adults",
    ],
    coolFeatures: [
      "Dark Horse gets flat-plane crank V8 borrowed from GT350",
      "Active valve exhaust can be set quiet for neighbors",
      "\"Good Day\" feature plays a custom start-up animation on the cluster",
    ],
    colors: ["Race Red", "Shadow Black", "Atlas Blue", "Vapor Blue", "Grabber Blue", "Oxford White", "Eruption Green"],
  },

  {
    id: "toyota-tundra-2024",
    brand: "Toyota",
    model: "Tundra",
    year: 2024,
    bodyStyle: "truck",
    fuelType: "hybrid",
    basePrice: 38520,
    maxPrice: 72310,
    image: "https://images.unsplash.com/photo-1618609740315-de8a9088ea77?w=800&q=80",
    tagline: "Toyota's full-size truck with a twin-turbo hybrid V6",
    description:
      "The 2024 Toyota Tundra ditches the old V8 for a twin-turbocharged hybrid V6 making 437 hp and a segment-leading 583 lb-ft of torque. It offers legendary Toyota reliability in a full-size truck package with class-competitive towing of 12,000 lbs.",
    specs: {
      horsepower: 437,
      torque: 583,
      engine: "3.5L Twin-Turbo V6 Hybrid (iForce MAX)",
      transmission: "10-Speed Automatic",
      driveType: "4WD",
      zeroToSixty: 5.5,
      topSpeed: 118,
      mpgCity: 19,
      mpgHighway: 24,
      mpgCombined: 21,
      cargo: 56.9,
      seating: 5,
      towingCapacity: 12000,
      payloadCapacity: 1940,
    },
    trimLevels: [
      { name: "SR", price: 38520, highlights: ["Twin-turbo V6", "8-inch display", "Toyota Safety Sense"] },
      { name: "SR5", price: 43220, highlights: ["18-inch wheels", "Power-adjustable seats", "Wireless CarPlay"] },
      { name: "Limited", price: 55000, highlights: ["14-inch touchscreen", "JBL audio", "360° camera"] },
      { name: "TRD Pro", price: 68000, highlights: ["Fox shocks", "Skid plates", "TRD exhaust"] },
      { name: "Capstone", price: 72310, highlights: ["Semi-aniline leather", "Panoramic moonroof", "Multi-terrain monitor"] },
    ],
    safety: {
      rating: "5",
      ratingSource: "NHTSA 2024",
      features: [
        "Toyota Safety Sense 2.5+",
        "Pre-Collision System",
        "Adaptive Cruise Control",
        "Blind Spot Monitor",
        "Rear Cross-Traffic Alert",
        "Automatic High Beams",
        "10 Airbags",
      ],
    },
    interiorFeatures: [
      "14-inch touchscreen (Limited+)",
      "Heated and ventilated seats",
      "JBL 12-speaker audio",
      "Wireless charging",
      "Multi-terrain select",
      "Electronic locking rear differential",
    ],
    exteriorFeatures: [
      "Composite bed with deck rail system",
      "LED headlights with LED DRLs",
      "Power-retractable running boards (Premium)",
      "20-inch aluminum wheels (Limited+)",
    ],
    techFeatures: [
      "14-inch Toyota Audio Multimedia system",
      "Wireless Apple CarPlay & Android Auto",
      "Toyota Remote Connect app",
      "360° bird's eye view camera",
      "Connected Services (Wi-Fi, Alexa)",
    ],
    pros: [
      "Industry-leading 583 lb-ft torque from the hybrid V6",
      "Toyota long-term reliability sets it apart",
      "Best-in-class fuel economy for full-size trucks (hybrid)",
      "12,000 lb towing capacity",
    ],
    cons: [
      "Ride quality is firm on SR/SR5",
      "Cabin storage not as clever as Ford's",
      "iForce MAX hybrid only on upper trims",
      "Smaller payload than Ram 1500 and F-150",
    ],
    coolFeatures: [
      "Multi-terrain camera shows underneath the truck during off-roading",
      "Bed step is built into the tailgate",
      "Power Tailgate available on TRD Pro",
    ],
    colors: ["Magnetic Gray", "Blueprint", "Midnight Black", "White", "Lunar Rock", "Supersonic Red"],
  },

  {
    id: "honda-odyssey-2024",
    brand: "Honda",
    model: "Odyssey",
    year: 2024,
    bodyStyle: "van",
    fuelType: "gasoline",
    basePrice: 37870,
    maxPrice: 52635,
    image: "https://images.unsplash.com/photo-1532564979029-bbf9fcbe7b0b?w=800&q=80",
    tagline: "The gold standard of family minivans",
    description:
      "The 2024 Honda Odyssey remains the benchmark family hauler. With seating for 8, a magic sliding second-row seat that creates a conversation zone between rows, built-in vacuum cleaner, and a refined 3.5L V6, it's the smartest van on the market.",
    specs: {
      horsepower: 280,
      torque: 262,
      engine: "3.5L V6",
      transmission: "10-Speed Automatic",
      driveType: "FWD",
      zeroToSixty: 7.0,
      topSpeed: 119,
      mpgCity: 19,
      mpgHighway: 28,
      mpgCombined: 22,
      cargo: 158,
      seating: 8,
    },
    trimLevels: [
      { name: "LX", price: 37870, highlights: ["V6 engine", "8-passenger seating", "Honda Sensing"] },
      { name: "EX", price: 42260, highlights: ["Power sliding doors", "Magic Slide 2nd row", "Apple CarPlay"] },
      { name: "EX-L", price: 46385, highlights: ["Leather seating", "Heated seats", "Rear entertainment system"] },
      { name: "Touring", price: 50785, highlights: ["CabinWatch camera", "CabinTalk intercom", "10.2-inch display"] },
      { name: "Elite", price: 52635, highlights: ["Built-in vacuum", "Panoramic roof", "18-inch wheels"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Honda Sensing Standard",
        "Collision Mitigation Braking",
        "Adaptive Cruise Control",
        "Lane Keeping Assist",
        "Road Departure Mitigation",
        "Blind Spot Information System",
        "Cross Traffic Monitor",
      ],
    },
    interiorFeatures: [
      "Magic Slide 2nd-row seat (EX+)",
      "Rear entertainment system (EX-L+)",
      "CabinWatch camera for rear rows",
      "CabinTalk intercom system",
      "HondaVAC built-in vacuum (Elite)",
      "Tri-zone automatic climate control",
    ],
    exteriorFeatures: [
      "Power sliding rear doors",
      "Power liftgate",
      "LED headlights",
      "18-inch alloy wheels (Elite)",
    ],
    techFeatures: [
      "10.2-inch touchscreen (Touring+)",
      "Wireless Apple CarPlay & Android Auto",
      "Wi-Fi hotspot",
      "Amazon Alexa built-in",
      "Rear USB-C charging ports",
    ],
    pros: [
      "Magic Slide seats create unique family-friendly layouts",
      "Best ride quality in the minivan segment",
      "V6 power feels effortless with 8 passengers",
      "Industry-first built-in vacuum cleaner",
      "Smartest interior storage solutions",
    ],
    cons: [
      "No hybrid option",
      "Not available in AWD",
      "Minivan stigma",
      "Fuel economy lags behind Toyota Sienna hybrid",
    ],
    coolFeatures: [
      "HondaVAC: built-in vacuum retracts from the cargo area",
      "Magic Slide seats can slide sideways to create a 'conversation' layout",
      "CabinTalk: driver's voice amplified to rear speakers like a built-in intercom",
    ],
    colors: ["Sonic Gray", "Lunar Silver", "Modern Steel", "Radiant Red", "Sonic Gray Pearl", "Platinum White"],
  },

  {
    id: "chevrolet-equinox-ev-2024",
    brand: "Chevrolet",
    model: "Equinox EV",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "electric",
    basePrice: 34995,
    maxPrice: 48995,
    image: "https://images.unsplash.com/photo-1697989716693-092a7ed5a21a?w=800&q=80",
    tagline: "The most affordable electric SUV in America",
    description:
      "The 2024 Chevrolet Equinox EV shakes up the market by bringing an electric SUV to the $35k price point. With up to 319 miles of range, a well-equipped cabin, and Google built-in, it democratizes EV ownership for mainstream buyers.",
    specs: {
      horsepower: 290,
      torque: 333,
      engine: "Single Front Electric Motor",
      transmission: "Single-Speed Automatic",
      driveType: "FWD",
      zeroToSixty: 6.0,
      topSpeed: 112,
      electricRange: 319,
      totalRange: 319,
      batteryCapacity: 85,
      chargingTime: "~40 min (10–80% DC Fast)",
      cargo: 57.3,
      seating: 5,
    },
    trimLevels: [
      { name: "1LT", price: 34995, highlights: ["319 mi range", "11-inch touchscreen", "Google built-in"] },
      { name: "2LT", price: 40995, highlights: ["Heated seats", "Wireless charging", "Bose audio"] },
      { name: "3LT", price: 44995, highlights: ["Panoramic sunroof", "Leather seats", "Enhanced Super Cruise"] },
      { name: "RS AWD", price: 48995, highlights: ["AWD", "0-60 in 5.3s", "Sport appearance"] },
    ],
    safety: {
      rating: "5",
      ratingSource: "NHTSA 2024",
      features: [
        "Automatic Emergency Braking",
        "Forward Collision Alert",
        "Lane Keep Assist",
        "Rear Park Assist",
        "Blind Zone Alert",
        "Rear Cross Traffic Alert",
        "Super Cruise hands-free driving (3LT+)",
      ],
    },
    interiorFeatures: [
      "11-inch infotainment + 11-inch driver display",
      "Google built-in (Maps, Assistant, Play Store)",
      "Heated front seats (2LT+)",
      "Wireless Apple CarPlay & Android Auto",
      "Wireless charging pad",
      "USB-C ports front and rear",
    ],
    exteriorFeatures: [
      "Sleek flush door handles",
      "Full LED lighting",
      "18-inch wheels",
      "Panoramic sunroof (3LT+)",
    ],
    techFeatures: [
      "Google built-in with native Maps",
      "myChevrolet app remote access",
      "Over-the-air updates",
      "Ultifi software platform",
      "Super Cruise hands-free driving",
    ],
    pros: [
      "Cheapest well-equipped EV SUV in the US",
      "319 miles of range at this price is remarkable",
      "Google built-in is best native infotainment available",
      "Spacious interior rivals gas SUVs",
    ],
    cons: [
      "DC fast charging speed limited to 150 kW",
      "GM's charging network not as reliable as Tesla",
      "No V2H (vehicle-to-home) power export",
      "Plastic-heavy interior at base trim",
    ],
    coolFeatures: [
      "Super Cruise offers true hands-free highway driving on 400,000+ miles of mapped roads",
      "Flat floor in the cabin — no transmission tunnel",
      "Qualifies for full $7,500 federal EV tax credit",
    ],
    colors: ["Summit White", "Mosaic Black", "Sterling Gray", "Riptide Blue", "Radiant Red", "Glacier Blue"],
  },

  {
    id: "ram-1500-2024",
    brand: "Ram",
    model: "1500",
    year: 2024,
    bodyStyle: "truck",
    fuelType: "gasoline",
    basePrice: 38135,
    maxPrice: 77285,
    image: "https://images.unsplash.com/photo-1672125052834-937014e540c2?w=800&q=80",
    tagline: "America's most comfortable full-size truck",
    description:
      "The 2024 Ram 1500 is the truck that redefined the segment with a coil-spring rear suspension for a car-like ride. With class-leading towing of 12,750 lbs, a luxurious Tungsten trim, and the available 3.0L Hurricane twin-turbo inline-six, it's as capable as it is comfortable.",
    specs: {
      horsepower: 420,
      torque: 469,
      engine: "3.0L Hurricane Twin-Turbo I6",
      transmission: "8-Speed Automatic",
      driveType: "4WD",
      zeroToSixty: 5.9,
      topSpeed: 118,
      mpgCity: 17,
      mpgHighway: 24,
      mpgCombined: 20,
      cargo: 53.9,
      seating: 5,
      towingCapacity: 12750,
      payloadCapacity: 2300,
    },
    trimLevels: [
      { name: "Tradesman", price: 38135, highlights: ["3.6L V6", "Work-focused", "Uconnect 5"] },
      { name: "Big Horn", price: 43000, highlights: ["12-inch touchscreen", "Remote start", "Sport appearance"] },
      { name: "Laramie", price: 52000, highlights: ["Leather seats", "Heated/cooled seats", "Alpine audio"] },
      { name: "TRX", price: 74000, highlights: ["702 hp Hellcat", "Fox shocks", "Off-road king"] },
      { name: "Tungsten", price: 77285, highlights: ["Night vision", "Massaging seats", "32-inch rear screen"] },
    ],
    safety: {
      rating: "5",
      ratingSource: "NHTSA 2024",
      features: [
        "Forward Collision Warning",
        "Automatic Emergency Braking",
        "Blind Spot Monitoring",
        "Rear Cross Path Detection",
        "Adaptive Cruise Control",
        "Night Vision (Tungsten)",
        "360° Surround View Camera",
      ],
    },
    interiorFeatures: [
      "12-inch Uconnect 5 touchscreen",
      "Available 32-inch rear-seat entertainment display",
      "Heated, ventilated, and massaging seats",
      "Panoramic sunroof",
      "RamBox cargo management system",
      "4-corner air suspension",
    ],
    exteriorFeatures: [
      "Active aero shutters for efficiency",
      "LED headlights with signature DRLs",
      "Multi-function tailgate",
      "20-inch chrome wheels (Laramie+)",
    ],
    techFeatures: [
      "Uconnect 5 with 12-inch touchscreen",
      "Wireless CarPlay & Android Auto",
      "Amazon Alexa integration",
      "Ram's Multifunction Tailgate with nine positions",
      "Available night vision camera",
    ],
    pros: [
      "Coil-spring rear suspension gives best ride in segment",
      "Best towing in class: 12,750 lbs",
      "Most luxurious interior of any truck (Tungsten)",
      "TRX is the most powerful production truck ever built",
    ],
    cons: [
      "Fuel economy lags Ford F-150 hybrid",
      "Complex option packages can inflate price quickly",
      "Larger turning radius than F-150",
    ],
    coolFeatures: [
      "TRX: 702 hp Hellcat engine in a production truck",
      "Tungsten trim includes 32-inch rear entertainment screen",
      "4-corner air suspension adjusts ride height automatically at speed",
    ],
    colors: ["Bright White", "Diamond Black", "Hydro Blue", "Patriot Blue", "Flame Red", "Billet Silver"],
  },

  {
    id: "volkswagen-id4-2024",
    brand: "Volkswagen",
    model: "ID.4",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "electric",
    basePrice: 38995,
    maxPrice: 50995,
    image: "https://images.unsplash.com/photo-1571872580550-5a0570339714?w=800&q=80",
    tagline: "German engineering meets everyday electric SUV",
    description:
      "The 2024 Volkswagen ID.4 brings European craftsmanship and a polished driving experience to the EV SUV segment. With up to 291 miles of range, available AWD, and a spacious interior, the ID.4 is a compelling alternative to the Model Y.",
    specs: {
      horsepower: 282,
      torque: 339,
      engine: "Dual Electric Motors",
      transmission: "Single-Speed Automatic",
      driveType: "AWD",
      zeroToSixty: 5.4,
      topSpeed: 112,
      electricRange: 255,
      totalRange: 255,
      batteryCapacity: 82,
      chargingTime: "~36 min (10–80% DC Fast)",
      cargo: 64.2,
      seating: 5,
    },
    trimLevels: [
      { name: "Standard", price: 38995, highlights: ["291 mi range (RWD)", "12-inch touchscreen", "Wireless CarPlay"] },
      { name: "Pro S", price: 44995, highlights: ["Panoramic roof", "Heated seats", "Harman Kardon audio"] },
      { name: "AWD Pro", price: 46995, highlights: ["AWD", "255 mi range", "5.4s 0-60"] },
      { name: "AWD Pro S+", price: 50995, highlights: ["21-inch wheels", "Massage seats", "Augmented reality HUD"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "IQ.DRIVE driver assistance suite",
        "Automatic Emergency Braking",
        "Blind Spot Monitor",
        "Rear Traffic Alert",
        "Lane Assist",
        "Travel Assist (semi-autonomous)",
        "Park Assist",
      ],
    },
    interiorFeatures: [
      "12-inch touchscreen with ID. Software",
      "Augmented reality head-up display (Pro S+)",
      "Harman Kardon audio system",
      "Heated front seats and steering wheel",
      "Panoramic glass roof (Pro S+)",
      "Large center console with hidden storage",
    ],
    exteriorFeatures: [
      "Sleek frameless doors",
      "Full LED IQ.LIGHT matrix headlights",
      "Flush door handles",
      "21-inch wheels (Pro S+)",
    ],
    techFeatures: [
      "ID. Software with OTA updates",
      "Wireless Apple CarPlay & Android Auto",
      "Augmented reality navigation HUD",
      "\"We Connect\" remote app",
      "Voice control with natural language",
    ],
    pros: [
      "Premium German interior quality",
      "Very smooth and quiet ride",
      "Qualifies for $7,500 federal tax credit",
      "Best-in-class cargo space for an EV SUV",
      "IIHS Top Safety Pick+",
    ],
    cons: [
      "Touchscreen controls can be distracting",
      "Charging speed not as fast as Hyundai/Kia 800V",
      "AWD reduces range to 255 miles",
      "Software update history has been buggy",
    ],
    coolFeatures: [
      "Augmented reality HUD overlays navigation arrows onto the road ahead",
      "Flat floor gives a truly airy, open interior feel",
      "Made in Tennessee — qualifies for federal EV tax credit",
    ],
    colors: ["Moonstone Gray", "Deep Black", "Kings Red", "Glacier White", "Dusk Blue", "Pomelo Yellow"],
  },

  {
    id: "mazda-cx5-2024",
    brand: "Mazda",
    model: "CX-5",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "gasoline",
    basePrice: 29150,
    maxPrice: 41050,
    image: "https://images.unsplash.com/photo-1687292625389-664f8c39586b?w=800&q=80",
    tagline: "The SUV that drives like a sports car",
    description:
      "The 2024 Mazda CX-5 is the driver's compact SUV — refined, premium-feeling, and exceptionally well-crafted for its price. With class-leading interior quality, available turbocharged engine, and AWD standard on most trims, it consistently rivals vehicles costing thousands more.",
    specs: {
      horsepower: 187,
      torque: 186,
      engine: "2.5L Skyactiv-G 4-Cylinder",
      transmission: "6-Speed Automatic",
      driveType: "AWD",
      zeroToSixty: 7.8,
      topSpeed: 124,
      mpgCity: 24,
      mpgHighway: 30,
      mpgCombined: 27,
      cargo: 59.6,
      seating: 5,
    },
    trimLevels: [
      { name: "2.5 S", price: 29150, highlights: ["FWD", "2.5L engine", "10.25-inch display"] },
      { name: "2.5 S Select", price: 31900, highlights: ["AWD standard", "Heated seats", "Bose audio"] },
      { name: "2.5 S Carbon Edition", price: 35000, highlights: ["Carbon trim", "Red Nappa leather", "Sport appearance"] },
      { name: "2.5 Turbo", price: 38000, highlights: ["256 hp turbo", "27 city / 35 hwy MPG", "All-weather"] },
      { name: "2.5 Turbo Signature", price: 41050, highlights: ["Parchment Nappa leather", "DVD navigation", "Frameless mirrors"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Mazda i-Activsense Safety Suite",
        "Smart Brake Support",
        "Lane-Keep Assist",
        "Blind Spot Monitoring",
        "Rear Cross Traffic Alert",
        "Driver Attention Alert",
        "360° View Monitor (Turbo Signature)",
      ],
    },
    interiorFeatures: [
      "10.25-inch infotainment (rotary dial control)",
      "Genuine wood trim accents (Signature)",
      "Nappa leather seats (Carbon/Signature)",
      "Heated and ventilated front seats",
      "Bose 10-speaker premium audio",
      "Dual-zone automatic climate",
    ],
    exteriorFeatures: [
      "Mazda's Kodo design language",
      "LED headlights with auto-leveling",
      "Roof rails",
      "19-inch alloy wheels",
    ],
    techFeatures: [
      "10.25-inch Mazda Connect infotainment",
      "Wireless Apple CarPlay (rotary/touch)",
      "Wireless Android Auto",
      "Mazda Connected Services",
      "Hands-free liftgate",
    ],
    pros: [
      "Interior quality rivals luxury brands",
      "Most engaging driving dynamics in the class",
      "Excellent standard safety features",
      "Premium feel without premium price",
      "IIHS Top Safety Pick+",
    ],
    cons: [
      "No hybrid or PHEV option",
      "Rear seat is tight for tall adults",
      "Infotainment rotary dial not intuitive for all users",
      "AWD not standard on base trim",
    ],
    coolFeatures: [
      "Turbo model achieves 35 MPG highway — rare for a turbocharged SUV",
      "Interior quality is often compared to Audi and Lexus at $10k less",
      "Cylinder deactivation tech shuts off 2 cylinders at cruise for efficiency",
    ],
    colors: ["Soul Red Crystal", "Polymetal Gray", "Jet Black Mica", "Rhodium White", "Platinum Quartz", "Deep Crystal Blue"],
  },

  {
    id: "genesis-gv80-2024",
    brand: "Genesis",
    model: "GV80",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "gasoline",
    basePrice: 56950,
    maxPrice: 79000,
    image: "https://images.unsplash.com/photo-1709104761873-24cc12d23b28?w=800&q=80",
    tagline: "Luxury SUV that redefines value",
    description:
      "The 2024 Genesis GV80 is the Korean luxury SUV punching squarely at the BMW X5 and Mercedes GLE — and winning on value. With a stunning interior, optional 3.5L twin-turbo V6, and a 5-year complimentary maintenance program, it's the most compelling luxury SUV deal on the market.",
    specs: {
      horsepower: 375,
      torque: 391,
      engine: "3.5L Twin-Turbo V6",
      transmission: "8-Speed Automatic",
      driveType: "AWD",
      zeroToSixty: 5.4,
      topSpeed: 149,
      mpgCity: 18,
      mpgHighway: 23,
      mpgCombined: 20,
      cargo: 43.4,
      seating: 5,
    },
    trimLevels: [
      { name: "2.5T Standard", price: 56950, highlights: ["2.5L turbo 4-cyl", "14.5-inch display", "AWD"] },
      { name: "2.5T Advanced", price: 64500, highlights: ["Heads-up display", "Relaxation seats", "Smart Sense+"] },
      { name: "3.5T Sport", price: 72000, highlights: ["375 hp V6", "21-inch wheels", "Sport tuning"] },
      { name: "3.5T Prestige", price: 79000, highlights: ["Premium Nappa leather", "360° surround view", "Ergo Motion seats"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Genesis Smart Sense suite",
        "Highway Driving Assist II",
        "Blind-Spot Collision Warning",
        "Rear Cross-Traffic Collision Warning",
        "Safe Exit Assist",
        "Driver Attention Warning",
        "Forward Collision Avoidance Assist",
      ],
    },
    interiorFeatures: [
      "14.5-inch curved infotainment display",
      "Full Nappa leather with quilted stitching",
      "Ergo Motion seats with 3D massage",
      "Bang & Olufsen 17-speaker audio",
      "Tri-zone automatic climate control",
      "Panoramic sunroof",
    ],
    exteriorFeatures: [
      "Crest grille with quad headlamps",
      "Two-line LED headlights (Genesis signature)",
      "20-inch or 22-inch wheels",
      "Frameless mirror cameras replacing door mirrors (optional)",
    ],
    techFeatures: [
      "14.5-inch touchscreen with fingerprint authentication",
      "Wireless Apple CarPlay & Android Auto",
      "Highway Driving Assist II (semi-autonomous)",
      "Over-the-air updates",
      "Remote Smart Parking Assist",
    ],
    pros: [
      "Interior rivals vehicles costing $20,000 more",
      "5-year / 60,000-mile free maintenance included",
      "Exceptional ride comfort",
      "Best value in luxury SUV segment",
      "Highway Driving Assist II best-in-class semi-autonomous tech",
    ],
    cons: [
      "Limited dealer network vs. BMW/Mercedes",
      "Brand recognition still catching up",
      "Rear cargo space slightly less than rivals",
      "No plug-in hybrid version yet",
    ],
    coolFeatures: [
      "Digital Side Mirrors replace glass mirrors with cameras for wider view",
      "Ergo Motion seats have 14 air cells that massage different posture zones",
      "Genesis Concierge service delivers and picks up your car for service",
    ],
    colors: ["Himalayan Gray", "Savile Silver", "Uyuni White", "Majestic Black", "Adriatic Blue", "Mona Lisa Red"],
  },

  {
    id: "ford-bronco-2024",
    brand: "Ford",
    model: "Bronco",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "gasoline",
    basePrice: 35000,
    maxPrice: 63000,
    image: "https://images.unsplash.com/photo-1677739115529-abf0fa4d3ea2?w=800&q=80",
    tagline: "Born wild. Built for the trail.",
    description:
      "The 2024 Ford Bronco brought back an icon and made it even more capable than the original. With removable doors and roof, a go-anywhere 4x4 system with up to 13.1 inches of ground clearance, and trail-specific tech, the Bronco redefines what a fun SUV can be.",
    specs: {
      horsepower: 330,
      torque: 415,
      engine: "2.7L EcoBoost V6",
      transmission: "7-Speed Manual / 10-Speed Automatic",
      driveType: "4WD",
      zeroToSixty: 5.5,
      topSpeed: 120,
      mpgCity: 17,
      mpgHighway: 21,
      mpgCombined: 19,
      cargo: 35.6,
      seating: 5,
      towingCapacity: 3500,
    },
    trimLevels: [
      { name: "Base", price: 35000, highlights: ["2.3L EcoBoost", "Removable doors & roof", "GOAT modes"] },
      { name: "Big Bend", price: 39000, highlights: ["Automatic 4x4", "Off-road suspension", "Wireless CarPlay"] },
      { name: "Outer Banks", price: 45000, highlights: ["Mid-high Terrain package", "Leather trim", "B&O audio"] },
      { name: "Wildtrak", price: 50000, highlights: ["Sasquatch Package standard", "Vinyl floor", "Locking rear diff"] },
      { name: "Raptor", price: 63000, highlights: ["418 hp", "Live Valve suspension", "37-inch tires"] },
    ],
    safety: {
      rating: "4",
      ratingSource: "NHTSA 2024",
      features: [
        "Pre-Collision Assist",
        "Automatic Emergency Braking",
        "Lane-Keeping System",
        "Blind Spot Information System",
        "Rear Cross-Traffic Alert",
        "Trail Control (adaptive cruise for off-road)",
      ],
    },
    interiorFeatures: [
      "12-inch SYNC 4 touchscreen (Big Bend+)",
      "Washable rubber floor (Wildtrak)",
      "Marine-grade vinyl seats",
      "B&O Sound System (Outer Banks+)",
      "Removable roof panels storage bag",
      "Grab handles throughout",
    ],
    exteriorFeatures: [
      "Removable hardtop or soft top",
      "Removable doors (all trims)",
      "Round LED headlights (heritage design)",
      "35- or 37-inch off-road tires (Sasquatch)",
      "Rock rails and skid plates",
    ],
    techFeatures: [
      "SYNC 4 with 12-inch touchscreen",
      "Trail Control cruise for off-road",
      "GOAT Modes (Goes Over Any Type of Terrain)",
      "360° camera for trail obstacles",
      "Ford Co-Pilot360 driver assistance",
    ],
    pros: [
      "Removable doors and roof for open-air fun",
      "Exceptional off-road capability out of the box",
      "Massive enthusiast community and aftermarket",
      "Raptor is the ultimate factory off-roader",
    ],
    cons: [
      "On-road ride is stiff",
      "Poor highway fuel economy",
      "Infotainment laggy at times",
      "Long wait times at dealers due to demand",
    ],
    coolFeatures: [
      "GOAT Modes (Goes Over Any Type of Terrain): 7 selectable off-road drive modes",
      "Trail Turn Assist: rear braking turns the front to make tighter trails manageable",
      "Sasquatch Package: 35-inch tires, locking diffs, lifted suspension — all factory",
    ],
    colors:["Cactus Gray", "Eruption Green", "Cyber Orange", "Area 51", "Hot Pepper Red", "Oxford White", "Shadow Black"],
  },

  {
    id: "hyundai-tucson-phev-2024",
    brand: "Hyundai",
    model: "Tucson PHEV",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "plug-in hybrid",
    basePrice: 38000,
    maxPrice: 44000,
    image: "https://images.unsplash.com/photo-1575090536203-2a6193126514?w=800&q=80",
    tagline: "Plug in, charge up, and go farther on less",
    description:
      "The 2024 Hyundai Tucson Plug-In Hybrid delivers the best of both worlds: 33 miles of all-electric range for daily commutes plus a gasoline engine for long trips, all wrapped in a handsome crossover body. It's one of the most practical PHEVs at this price point.",
    specs: {
      horsepower: 261,
      torque: 258,
      engine: "1.6L Turbo 4-Cylinder + Electric Motor",
      transmission: "6-Speed Automatic",
      driveType: "AWD",
      zeroToSixty: 6.7,
      topSpeed: 118,
      electricRange: 33,
      totalRange: 440,
      batteryCapacity: 13.8,
      chargingTime: "~1.9 hrs (Level 2 AC)",
      mpgCity: 35,
      mpgHighway: 38,
      mpgCombined: 36,
      cargo: 66.3,
      seating: 5,
    },
    trimLevels: [
      { name: "Blue", price: 38000, highlights: ["PHEV powertrain", "AWD standard", "33 mi EV range"] },
      { name: "SEL", price: 42000, highlights: ["Leather seats", "Wireless charging", "Panoramic sunroof"] },
      { name: "Limited", price: 44000, highlights: ["Bose audio", "Digital key", "Full LED interior"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK+",
      ratingSource: "IIHS 2024",
      features: [
        "Hyundai SmartSense",
        "Forward Collision-Avoidance Assist",
        "Lane Keeping Assist",
        "Blind-Spot Collision Warning",
        "Safe Exit Warning",
        "Rear Cross-Traffic Collision Warning",
        "Driver Attention Warning",
      ],
    },
    interiorFeatures: [
      "10.25-inch touchscreen",
      "Wireless Apple CarPlay & Android Auto",
      "Heated front and rear seats (SEL+)",
      "Dual-zone climate control",
      "Panoramic sunroof (SEL+)",
      "Wireless charging",
    ],
    exteriorFeatures: [
      "Parametric hidden lighting (front & rear)",
      "Seamless hidden door handles",
      "18-inch alloy wheels",
      "LED headlights",
    ],
    techFeatures: [
      "Hyundai Digital Key (phone as key)",
      "Bluelink connected car app",
      "Over-the-air software updates",
      "10.25-inch display with navigation",
    ],
    pros: [
      "33 miles EV range covers most daily commutes on electricity alone",
      "AWD standard on all PHEV trims",
      "440 miles total range eliminates range anxiety",
      "Beautiful and unique interior design",
      "IIHS Top Safety Pick+",
    ],
    cons: [
      "EV-only range shorter than some rivals",
      "Charging takes under 2 hrs (Level 2) — no DC fast charge",
      "Slightly less cargo space than non-PHEV Tucson",
      "PHEV premium adds ~$5k vs. standard hybrid",
    ],
    coolFeatures: [
      "Charge in most overnight stops — wake up with a full EV battery",
      "Seamless transition between electric and gas is completely invisible",
      "Solar roof on some international variants (US gets standard glass)",
    ],
    colors: ["Shimmering Silver", "Phantom Black", "Titan Gray", "Amazon Gray", "Deep Sea", "Serenity White"],
  },

  {
    id: "nissan-ariya-2024",
    brand: "Nissan",
    model: "Ariya",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "electric",
    basePrice: 39125,
    maxPrice: 60125,
    image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
    tagline: "Nissan's bold step into the electric future",
    description:
      "The 2024 Nissan Ariya is Nissan's flagship EV — a stylish, tech-forward electric crossover with up to 304 miles of range and a serene, minimalist interior. It combines Japanese attention to detail with smooth e-AWD performance for an everyday EV that impresses.",
    specs: {
      horsepower: 389,
      torque: 442,
      engine: "Dual Electric Motors (e-4ORCE)",
      transmission: "Single-Speed Automatic",
      driveType: "AWD",
      zeroToSixty: 5.1,
      topSpeed: 124,
      electricRange: 265,
      totalRange: 265,
      batteryCapacity: 87,
      chargingTime: "~37 min (10–80% DC Fast)",
      cargo: 59.3,
      seating: 5,
    },
    trimLevels: [
      { name: "Engage RWD", price: 39125, highlights: ["304 mi range", "12.3-inch displays", "ProPilot Assist"] },
      { name: "Venture+", price: 46125, highlights: ["87 kWh battery", "Heated seats", "Bose audio"] },
      { name: "Empower+ AWD", price: 54125, highlights: ["AWD", "389 hp", "265 mi range"] },
      { name: "Platinum+ AWD", price: 60125, highlights: ["Quilted leather", "Head-up display", "22-inch wheels"] },
    ],
    safety: {
      rating: "5",
      ratingSource: "NHTSA 2024",
      features: [
        "Nissan Safety Shield 360",
        "ProPilot Assist (hands-on semi-autonomous)",
        "Automatic Emergency Braking",
        "Blind Spot Warning",
        "Rear Cross Traffic Alert",
        "Lane Departure Warning",
        "Rear Automatic Braking",
      ],
    },
    interiorFeatures: [
      "Dual 12.3-inch screens (instrument + infotainment)",
      "Zero Gravity heated/cooled front seats",
      "Sliding center console",
      "Bose 10-speaker audio (Venture+)",
      "Ambient lighting with 64-color options",
      "Flat floor cabin from EV platform",
    ],
    exteriorFeatures: [
      "Flush hidden door handles",
      "Full LED lighting with arrow-shaped elements",
      "Aerodynamic 20-inch wheels",
      "Panoramic glass roof",
    ],
    techFeatures: [
      "ProPilot Assist 2.0 (highway hands-free)",
      "NissanConnect EV app",
      "Wireless Apple CarPlay & Android Auto",
      "Navigation with EV route planning",
      "Over-the-air updates",
    ],
    pros: [
      "Stunning interior design — unlike anything in the segment",
      "304 miles range on base RWD trim",
      "e-4ORCE AWD is incredibly composed on wet and slippery roads",
      "Sliding center console is genuinely useful",
    ],
    cons: [
      "Max 130 kW DC charging speed (slower than VW ID.4 or Ioniq 5)",
      "Nissan's charging network is third-party dependent",
      "AWD range drops significantly vs. RWD",
      "Rear seat a bit narrow for three adults",
    ],
    coolFeatures: [
      "Sliding center console moves forward to open up cabin for easy exit",
      "Zero Gravity seats modeled after NASA astronaut seating posture",
      "e-4ORCE AWD independently controls torque to each wheel in corners",
    ],
    colors: ["Pearl White", "Midnight Black", "Scarlet Ember", "Stealth Gray", "Nimbus Gray", "Monarch Orange"],
  },

  {
    id: "audi-q5-2024",
    brand: "Audi",
    model: "Q5",
    year: 2024,
    bodyStyle: "suv",
    fuelType: "plug-in hybrid",
    basePrice: 46895,
    maxPrice: 59995,
    image: "https://images.unsplash.com/photo-1622701579527-dcd1bb5fbb9b?w=800&q=80",
    tagline: "German luxury SUV with plug-in efficiency",
    description:
      "The 2024 Audi Q5 TFSI e combines a turbocharged 2.0L engine with an electric motor for 362 combined horsepower and 38 miles of EV range. It wraps this efficient powertrain in Audi's signature quattro AWD and a cabin full of premium materials and cutting-edge technology.",
    specs: {
      horsepower: 362,
      torque: 369,
      engine: "2.0L TFSI + Electric Motor (PHEV)",
      transmission: "7-Speed S tronic",
      driveType: "AWD",
      zeroToSixty: 5.0,
      topSpeed: 130,
      electricRange: 38,
      totalRange: 410,
      batteryCapacity: 14.1,
      chargingTime: "~2.0 hrs (Level 2 AC)",
      mpgCity: 27,
      mpgHighway: 31,
      mpgCombined: 29,
      cargo: 57.3,
      seating: 5,
    },
    trimLevels: [
      { name: "45 TFSI e Premium", price: 46895, highlights: ["38 mi EV range", "AWD quattro", "MMI infotainment"] },
      { name: "45 TFSI e Premium Plus", price: 52895, highlights: ["Bang & Olufsen audio", "Panoramic roof", "Head-up display"] },
      { name: "55 TFSI e Prestige", price: 59995, highlights: ["362 hp", "Night vision assist", "Valcona leather"] },
    ],
    safety: {
      rating: "TOP SAFETY PICK",
      ratingSource: "IIHS 2024",
      features: [
        "Audi pre sense front and city",
        "Adaptive Cruise Assist",
        "Lane Departure Warning",
        "Blind Spot Monitor",
        "Rear Cross Traffic Assist",
        "Park Assist with 360° cameras",
        "Night Vision Assistant (Prestige)",
      ],
    },
    interiorFeatures: [
      "10.1-inch MMI touchscreen",
      "12.3-inch virtual cockpit digital cluster",
      "Valcona leather seats (Prestige)",
      "Heated and massaging front seats",
      "Bang & Olufsen 3D audio (Premium Plus)",
      "4-zone climate control",
    ],
    exteriorFeatures: [
      "Matrix LED headlights",
      "Audi exclusive paint options",
      "20-inch alloy wheels",
      "Panoramic sunroof (Premium Plus)",
    ],
    techFeatures: [
      "MMI Navigation Plus with satellite maps",
      "Virtual Cockpit Plus",
      "Wireless Apple CarPlay & Android Auto",
      "myAudi app with remote charging scheduling",
      "Augmented reality navigation HUD",
    ],
    pros: [
      "38 miles EV range handles most daily commutes",
      "Quattro AWD gives exceptional all-weather confidence",
      "Best-in-class interior luxury",
      "410-mile total range removes any range anxiety",
    ],
    cons: [
      "Premium price for a PHEV",
      "DC fast charging not available",
      "Infotainment touchscreen replaces physical buttons awkwardly",
      "Audi service costs are high long-term",
    ],
    coolFeatures: [
      "Predictive efficiency assist: navigation uses map data to pre-charge or pre-brake",
      "Quattro ultra AWD disconnects rear axle on highway for efficiency",
      "myAudi app schedules charging during off-peak electricity hours",
    ],
    colors: ["Glacier White", "Mythos Black", "Florett Silver", "Navarra Blue", "Daytona Gray", "Siam Beige"],
  },
]

export function getCarById(id: string): Car | undefined {
  return cars.find((car) => car.id === id)
}

export function searchCars(params: {
  query?: string
  brand?: string
  bodyStyle?: string
  fuelType?: string
  minPrice?: number
  maxPrice?: number
  minHorsepower?: number
  seating?: number
}): Car[] {
  return cars.filter((car) => {
    if (params.query) {
      const q = params.query.toLowerCase()
      if (
        !car.brand.toLowerCase().includes(q) &&
        !car.model.toLowerCase().includes(q) &&
        !car.description.toLowerCase().includes(q) &&
        !car.bodyStyle.toLowerCase().includes(q) &&
        !car.fuelType.toLowerCase().includes(q)
      )
        return false
    }
    if (params.brand && car.brand.toLowerCase() !== params.brand.toLowerCase()) return false
    if (params.bodyStyle && car.bodyStyle !== params.bodyStyle) return false
    if (params.fuelType && car.fuelType !== params.fuelType) return false
    if (params.minPrice && car.basePrice < params.minPrice) return false
    if (params.maxPrice && car.basePrice > params.maxPrice) return false
    if (params.minHorsepower && car.specs.horsepower < params.minHorsepower) return false
    if (params.seating && car.specs.seating < params.seating) return false
    return true
  })
}

export const brands = Array.from(new Set(cars.map((c) => c.brand))).sort()
export const bodyStyles = Array.from(new Set(cars.map((c) => c.bodyStyle))).sort()
export const fuelTypes = Array.from(new Set(cars.map((c) => c.fuelType))).sort()

export { MAINSTREAM_BRANDS } from "./nhtsa"
